{% set name = "apache-airflow-providers-google" %}
{% set version = "10.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_google-{{ version }}.tar.gz
  sha256: bb71a18c5375bde68d915d0d9eef4422bbc018c08ae5ee68f4c93b2c8b61e07a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - pyopenssl
    - apache-airflow-providers-common-sql >=1.7.2
    - apache-airflow >=2.7.0
    - asgiref >=3.5.2
    - gcloud-aio-auth >=4.0.0,<5.0.0
    - gcloud-aio-bigquery >=6.1.2
    - gcloud-aio-storage >=9.0.0
    - gcsfs >=2023.10.0
    - google-ads >=23.1.0
    - google-analytics-admin
    - google-api-core >=2.11.0,!=2.16.0,!=2.18.0
    - google-api-python-client >=1.6.0
    - google-auth-httplib2 >=0.0.1
    - google-auth >=1.0.0
    - google-cloud-aiplatform >=1.42.1
    - google-cloud-automl >=2.12.0
    - google-cloud-batch >=0.13.0
    - google-cloud-bigquery-core <3.21.0,>=3.0.1
    - google-cloud-bigquery-datatransfer >=3.13.0
    - google-cloud-bigtable >=2.17.0
    - google-cloud-build >=3.22.0
    - google-cloud-compute >=1.10.0
    - google-cloud-container >=2.17.4
    - google-cloud-datacatalog >=3.11.1
    - google-cloud-dataflow-client >=0.8.6
    - google-cloud-dataform >=0.5.0
    - google-cloud-dataplex >=1.10.0
    - google-cloud-dataproc-metastore >=1.12.0
    - google-cloud-dataproc >=5.8.0
    - google-cloud-dlp >=3.12.0
    - google-cloud-kms >=2.15.0
    - google-cloud-language >=2.9.0
    - google-cloud-logging >=3.5.0
    - google-cloud-memcache >=1.7.0
    - google-cloud-monitoring >=2.18.0
    - google-cloud-orchestration-airflow >=1.10.0
    - google-cloud-os-login >=2.9.1
    - google-cloud-pubsub >=2.19.0
    - google-cloud-redis >=2.12.0
    - google-cloud-run >=0.9.0
    - google-cloud-secret-manager >=2.16.0
    - google-cloud-spanner >=3.11.1
    - google-cloud-speech >=2.18.0
    - google-cloud-storage-transfer >=1.4.1
    - google-cloud-storage >=2.7.0
    - google-cloud-tasks >=2.13.0
    - google-cloud-texttospeech >=2.14.1
    - google-cloud-translate >=3.11.0
    - google-cloud-videointelligence >=2.11.0
    - google-cloud-vision >=3.4.0
    - google-cloud-workflows >=1.10.0
    - grpcio-gcp >=0.2.2
    - httpx
    - json-merge-patch >=0.2
    - looker-sdk >=22.2.0
    - pandas-gbq
    - pandas >=1.2.5,<2.2
    - proto-plus >=1.19.6
    - python-slugify >=5.0
    - sqlalchemy-bigquery >=1.2.1
    - sqlalchemy-spanner >=1.6.2

    # googleapis-common-protos 1.57.0 has incorrect dependencies and doesn't seem worth fixing
    - googleapis-common-protos !=1.57.0

test:
  imports:
    - airflow.providers.google
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-google for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/google/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-google/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
