{% set name = "apache-airflow-providers-google" %}
{% set version = "17.1.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_google-{{ version }}.tar.gz
  sha256: 6545e08c8b056401dac9b24da6ec20c37d3b7dd1cb8158546c67262bbf1cd5eb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.12.0
    - pip
  run:
    - python >={{ python_min }}
    - apache-airflow >=2.10.0
    - apache-airflow-providers-common-compat >=1.4.0
    - apache-airflow-providers-common-sql >=1.27.0
    - asgiref >=3.5.2
    - dill >=0.2.3
    - gcloud-aio-auth >=5.2.0
    - gcloud-aio-bigquery >=6.1.2
    - gcloud-aio-storage >=9.0.0
    - gcsfs >=2023.10.0
    - google-ads >=26.0.0
    - google-analytics-admin >=0.9.0
    - google-api-core >=2.11.0,!=2.16.0,!=2.18.0
    - google-api-python-client >=2.0.2
    - google-auth >=2.29.0
    - google-auth-httplib2 >=0.0.1
    - google-cloud-aiplatform >=1.73.0

    # google-cloud-aiplatform[evaluation]
    - pandas >=1.0.0
    # more restrictive for python <= 3.10
    - scikit-learn <1.6.0
    - jsonschema
    - ruamel.yaml
    - pyyaml
    - litellm >=1.72.4

    - google-cloud-alloydb >=0.4.0
    - google-cloud-automl >=2.12.0
    - google-cloud-bigquery-core >=3.24.0
    - google-cloud-bigquery-datatransfer >=3.13.0
    - google-cloud-bigquery-storage >=2.31.0
    - google-cloud-bigtable >=2.17.0
    - google-cloud-build >=3.31.0
    - google-cloud-compute >=1.10.0
    - google-cloud-container >=2.52.0
    - google-cloud-datacatalog >=3.23.0
    - google-cloud-dataflow-client >=0.8.6
    - google-cloud-dataform >=0.5.0
    - google-cloud-dataplex >=2.6.0
    - google-cloud-dataproc >=5.12.0
    - google-cloud-dataproc-metastore >=1.12.0
    - google-cloud-dlp >=3.12.0
    - google-cloud-kms >=2.15.0
    - google-cloud-language >=2.9.0
    - google-cloud-logging >=3.5.0
    - google-cloud-managedkafka >=0.1.6
    - google-cloud-memcache >=1.7.0
    - google-cloud-monitoring >=2.18.0
    - google-cloud-orchestration-airflow >=1.10.0
    - google-cloud-os-login >=2.9.1
    - google-cloud-pubsub >=2.21.3
    - google-cloud-redis >=2.12.0
    - google-cloud-secret-manager >=2.16.0
    - google-cloud-spanner >=3.50.0
    - google-cloud-speech >=2.18.0
    - google-cloud-storage >=2.9.0
    - google-cloud-storage-transfer >=1.13.0
    - google-cloud-tasks >=2.13.0
    - google-cloud-texttospeech >=2.14.1
    - google-cloud-translate >=3.16.0
    - google-cloud-videointelligence >=2.11.0
    - google-cloud-vision >=3.4.0
    - google-cloud-workflows >=1.10.0
    - google-cloud-run >=0.10.0
    - google-cloud-batch >=0.13.0
    - grpcio-gcp >=0.2.2
    - httpx >=0.25.0
    - looker-sdk >=22.4.0,!=24.18.0
    - pandas-gbq >=0.7.0
    # more restrictive constraints for python >= 3.13
    - pandas >=2.2.3
    - proto-plus >=1.26.0
    # more restrictive constraints for python >= 3.13
    - pyarrow >=18.0.0
    - python-slugify >=7.0.0
    - pyopenssl >=23.0.0
    - ray-default >=2.42.0

    - sqlalchemy-bigquery >=1.2.1
    - sqlalchemy-spanner >=1.6.2
    - tenacity >=8.3.0
    - immutabledict >=4.2.0
    - types-protobuf !=5.29.1.20250402,>=5.27.0

    # googleapis-common-protos 1.57.0 has incorrect dependencies and doesn't seem worth fixing
    - googleapis-common-protos !=1.57.0

    # earlier versions ahve incorrect dependencies that don't seem worth fixing
    - opentelemetry-exporter-prometheus >=0.56b0

test:
  imports:
    - airflow.providers.google
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-google for Apache Airflow
  license: Apache-2.0 AND BSD-3-Clause AND MIT
  license_file:
    - src/airflow/providers/google/LICENSE
    - src/airflow/providers/google/3rd-party-licenses/LICENSES.txt
    - src/airflow/providers/google/3rd-party-licenses/NOTICE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-google/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
